[CmdletBinding()]
param(
  [string] $OutputPath = (Join-Path $PSScriptRoot 'generated/glyph-set-gallery.tape')
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repositoryRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../..'))
Import-Module (Join-Path $repositoryRoot 'src/gly.psd1') -Force

$glyphSetNames = [System.Collections.Generic.List[string]]::new()
foreach ($glyphSet in Get-GlyGlyphSet | Where-Object BuiltIn) {
  $glyphSetNames.Add($glyphSet.Name)
}
$glyphSetNames.Sort([System.StringComparer]::Ordinal)

function ConvertTo-CaptureSlug {
  param([Parameter(Mandatory)][string] $Name)

  (($Name -creplace '([a-z0-9])([A-Z])', '$1-$2') -replace '[^A-Za-z0-9]+', '-').Trim('-').ToLowerInvariant()
}

New-Item -ItemType Directory -Path (Join-Path $repositoryRoot 'assets/captures/glyph-sets') -Force | Out-Null
New-Item -ItemType Directory -Path (Split-Path -Parent $OutputPath) -Force | Out-Null

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('# Generated by scripts/capture/New-GlyGlyphSetGalleryTape.ps1. Do not edit.')
$lines.Add('Output artifacts/captures/glyph-set-gallery.gif')
$lines.Add('Require pwsh')
$lines.Add('Set Shell pwsh')
$lines.Add('Set Width 1000')
$lines.Add('Set Height 620')
$lines.Add('Set FontFamily "JetBrainsMono Nerd Font Mono"')
$lines.Add('Set FontSize 18')
$lines.Add('Set LineHeight 1.2')
$lines.Add('Set TypingSpeed 0ms')
$lines.Add('Set Framerate 30')
$lines.Add('Set CursorBlink false')
$lines.Add('Set Theme "Catppuccin Mocha"')
$lines.Add('')
$lines.Add('Hide')
$lines.Add('Type "$env:TERM = ''xterm-256color''"')
$lines.Add('Enter')
$lines.Add('Type "$env:COLORTERM = ''truecolor''"')
$lines.Add('Enter')
$lines.Add('Type "$env:LANG = ''C.UTF-8''"')
$lines.Add('Enter')
$lines.Add('Type "$ProgressPreference = ''SilentlyContinue''"')
$lines.Add('Enter')
$lines.Add('Type "Import-Module ./src/gly.psd1 -Force"')
$lines.Add('Enter')
$lines.Add('Type "$global:GlyStyleRenderer = ''Ansi''"')
$lines.Add('Enter')
$lines.Add('Type "function global:prompt { ''PS> '' }"')
$lines.Add('Enter')
$lines.Add('Type "Clear-Host"')
$lines.Add('Enter')
$lines.Add('Show')
$lines.Add('')

foreach ($glyphSetName in $glyphSetNames) {
  $screenshotPath = "assets/captures/glyph-sets/$(ConvertTo-CaptureSlug $glyphSetName).png"
  $lines.Add("Type `"Clear-Host; Show-GlyThemePreview -Theme DefaultDark -GlyphSet $glyphSetName`"")
  $lines.Add('Enter')
  $lines.Add('Wait+Screen /Directory/')
  $lines.Add("Screenshot $screenshotPath")
  $lines.Add('Sleep 250ms')
  $lines.Add('')
}

[System.IO.File]::WriteAllLines(
  [System.IO.Path]::GetFullPath($OutputPath),
  $lines,
  [System.Text.UTF8Encoding]::new($false)
)
