[CmdletBinding()]
param(
  [string] $OutputDirectory = (Join-Path $PSScriptRoot 'generated'),

  [string] $ThemeManifestPath = (Join-Path $PSScriptRoot 'ThemeBackgrounds.psd1')
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repositoryRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../..'))
$themeBackgrounds = Import-PowerShellDataFile -Path $ThemeManifestPath

foreach ($background in @('Dark', 'Light')) {
  if (-not $themeBackgrounds.ContainsKey($background)) {
    throw "The theme background manifest must contain a '$background' entry."
  }
}

Import-Module (Join-Path $repositoryRoot 'src/gly.psd1') -Force

$themeNames = [System.Collections.Generic.List[string]]::new()
foreach ($theme in Get-GlyTheme | Where-Object BuiltIn) {
  $themeNames.Add($theme.Name)
}
$themeNames.Sort([System.StringComparer]::Ordinal)

$backgroundByTheme = @{}
foreach ($background in @('Dark', 'Light')) {
  foreach ($themeName in $themeBackgrounds[$background]) {
    if ($backgroundByTheme.ContainsKey($themeName)) {
      throw "Theme '$themeName' is assigned more than one capture background."
    }
    $backgroundByTheme[$themeName] = $background
  }
}

$unclassified = @($themeNames | Where-Object { -not $backgroundByTheme.ContainsKey($_) })
$unknown = @($backgroundByTheme.Keys | Where-Object { $_ -notin $themeNames })
if ($unclassified.Count -gt 0 -or $unknown.Count -gt 0) {
  $problems = @()
  if ($unclassified.Count -gt 0) { $problems += "unclassified: $($unclassified -join ', ')" }
  if ($unknown.Count -gt 0) { $problems += "unknown: $($unknown -join ', ')" }
  throw "Theme capture manifest does not match built-in themes ($($problems -join '; '))."
}

function ConvertTo-CaptureSlug {
  param([Parameter(Mandatory)][string] $Name)

  (($Name -creplace '([a-z0-9])([A-Z])', '$1-$2') -replace '[^A-Za-z0-9]+', '-').Trim('-').ToLowerInvariant()
}

$captureDirectory = Join-Path $repositoryRoot 'assets/captures/themes'
New-Item -ItemType Directory -Path $captureDirectory -Force | Out-Null
New-Item -ItemType Directory -Path $OutputDirectory -Force | Out-Null

function New-ThemeGalleryTape {
  param(
    [Parameter(Mandatory)][string] $Background,
    [Parameter(Mandatory)][System.Collections.Generic.List[string]] $Names
  )

  $terminalTheme = if ($Background -eq 'Dark') { 'Catppuccin Mocha' } else { 'Catppuccin Latte' }
  $lines = [System.Collections.Generic.List[string]]::new()
  $lines.Add('# Generated by scripts/capture/New-GlyThemeGalleryTape.ps1. Do not edit.')
  $lines.Add("Output artifacts/captures/theme-gallery-$($Background.ToLowerInvariant()).gif")
  $lines.Add('Require pwsh')
  $lines.Add('Set Shell pwsh')
  $lines.Add('Set Width 1000')
  $lines.Add('Set Height 620')
  $lines.Add('Set FontFamily "JetBrainsMono Nerd Font Mono"')
  $lines.Add('Set FontSize 18')
  $lines.Add('Set LineHeight 1.2')
  $lines.Add('Set TypingSpeed 0ms')
  $lines.Add('Set Framerate 30')
  $lines.Add('Set CursorBlink false')
  $lines.Add("Set Theme `"$terminalTheme`"")
  $lines.Add('')
  $lines.Add('Hide')
  $lines.Add('Type "$env:TERM = ''xterm-256color''"')
  $lines.Add('Enter')
  $lines.Add('Type "$env:COLORTERM = ''truecolor''"')
  $lines.Add('Enter')
  $lines.Add('Type "$env:LANG = ''C.UTF-8''"')
  $lines.Add('Enter')
  $lines.Add('Type "$ProgressPreference = ''SilentlyContinue''"')
  $lines.Add('Enter')
  $lines.Add('Type "Import-Module ./src/gly.psd1 -Force"')
  $lines.Add('Enter')
  $lines.Add('Type "$global:GlyStyleRenderer = ''Ansi''"')
  $lines.Add('Enter')
  $lines.Add('Type "function global:prompt { ''PS> '' }"')
  $lines.Add('Enter')
  $lines.Add('Type "Clear-Host"')
  $lines.Add('Enter')
  $lines.Add('Show')
  $lines.Add('')

  foreach ($themeName in $Names) {
    $screenshotPath = "assets/captures/themes/$(ConvertTo-CaptureSlug $themeName).png"
    $lines.Add("Type `"Clear-Host; Show-GlyThemePreview -Theme $themeName -GlyphSet NerdFonts | Select-Object -First 12; Write-Output ('Theme' + ': ' + '$themeName')`"")
    $lines.Add('Enter')
    $lines.Add("Wait+Screen /Theme: $themeName/")
    $lines.Add("Screenshot $screenshotPath")
    $lines.Add('Sleep 250ms')
    $lines.Add('')
  }

  $outputPath = Join-Path $OutputDirectory "theme-gallery-$($Background.ToLowerInvariant()).tape"
  [System.IO.File]::WriteAllLines(
    [System.IO.Path]::GetFullPath($outputPath),
    $lines,
    [System.Text.UTF8Encoding]::new($false)
  )
}

foreach ($background in @('Dark', 'Light')) {
  $names = [System.Collections.Generic.List[string]]::new()
  foreach ($themeName in $themeNames) {
    if ($backgroundByTheme[$themeName] -eq $background) { $names.Add($themeName) }
  }
  New-ThemeGalleryTape -Background $background -Names $names
}
